// Code generated by thriftgo (0.3.2). DO NOT EDIT.

package api

import (
	"context"
	"fmt"
	"github.com/apache/thrift/lib/go/thrift"
	"kitexserver/kitex_gen/dragon"
)

type Sample interface {
	DragonSay(ctx context.Context, req *dragon.DragonSayRequest) (r *dragon.DragonSayResponse, err error)
}

type SampleClient struct {
	c thrift.TClient
}

func NewSampleClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *SampleClient {
	return &SampleClient{
		c: thrift.NewTStandardClient(f.GetProtocol(t), f.GetProtocol(t)),
	}
}

func NewSampleClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *SampleClient {
	return &SampleClient{
		c: thrift.NewTStandardClient(iprot, oprot),
	}
}

func NewSampleClient(c thrift.TClient) *SampleClient {
	return &SampleClient{
		c: c,
	}
}

func (p *SampleClient) Client_() thrift.TClient {
	return p.c
}

func (p *SampleClient) DragonSay(ctx context.Context, req *dragon.DragonSayRequest) (r *dragon.DragonSayResponse, err error) {
	var _args SampleDragonSayArgs
	_args.Req = req
	var _result SampleDragonSayResult
	if err = p.Client_().Call(ctx, "dragonSay", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

type SampleProcessor struct {
	processorMap map[string]thrift.TProcessorFunction
	handler      Sample
}

func (p *SampleProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
	p.processorMap[key] = processor
}

func (p *SampleProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
	processor, ok = p.processorMap[key]
	return processor, ok
}

func (p *SampleProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
	return p.processorMap
}

func NewSampleProcessor(handler Sample) *SampleProcessor {
	self := &SampleProcessor{handler: handler, processorMap: make(map[string]thrift.TProcessorFunction)}
	self.AddToProcessorMap("dragonSay", &sampleProcessorDragonSay{handler: handler})
	return self
}
func (p *SampleProcessor) Process(ctx context.Context, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	name, _, seqId, err := iprot.ReadMessageBegin()
	if err != nil {
		return false, err
	}
	if processor, ok := p.GetProcessorFunction(name); ok {
		return processor.Process(ctx, seqId, iprot, oprot)
	}
	iprot.Skip(thrift.STRUCT)
	iprot.ReadMessageEnd()
	x := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function "+name)
	oprot.WriteMessageBegin(name, thrift.EXCEPTION, seqId)
	x.Write(oprot)
	oprot.WriteMessageEnd()
	oprot.Flush(ctx)
	return false, x
}

type sampleProcessorDragonSay struct {
	handler Sample
}

func (p *sampleProcessorDragonSay) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	args := SampleDragonSayArgs{}
	if err = args.Read(iprot); err != nil {
		iprot.ReadMessageEnd()
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
		oprot.WriteMessageBegin("dragonSay", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return false, err
	}

	iprot.ReadMessageEnd()
	var err2 error
	result := SampleDragonSayResult{}
	var retval *dragon.DragonSayResponse
	if retval, err2 = p.handler.DragonSay(ctx, args.Req); err2 != nil {
		x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing dragonSay: "+err2.Error())
		oprot.WriteMessageBegin("dragonSay", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return true, err2
	} else {
		result.Success = retval
	}
	if err2 = oprot.WriteMessageBegin("dragonSay", thrift.REPLY, seqId); err2 != nil {
		err = err2
	}
	if err2 = result.Write(oprot); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.Flush(ctx); err == nil && err2 != nil {
		err = err2
	}
	if err != nil {
		return
	}
	return true, err
}

type SampleDragonSayArgs struct {
	Req *dragon.DragonSayRequest `thrift:"req,1" frugal:"1,default,dragon.DragonSayRequest" json:"req"`
}

func NewSampleDragonSayArgs() *SampleDragonSayArgs {
	return &SampleDragonSayArgs{}
}

func (p *SampleDragonSayArgs) InitDefault() {
	*p = SampleDragonSayArgs{}
}

var SampleDragonSayArgs_Req_DEFAULT *dragon.DragonSayRequest

func (p *SampleDragonSayArgs) GetReq() (v *dragon.DragonSayRequest) {
	if !p.IsSetReq() {
		return SampleDragonSayArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *SampleDragonSayArgs) SetReq(val *dragon.DragonSayRequest) {
	p.Req = val
}

var fieldIDToName_SampleDragonSayArgs = map[int16]string{
	1: "req",
}

func (p *SampleDragonSayArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SampleDragonSayArgs) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}

		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_SampleDragonSayArgs[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *SampleDragonSayArgs) ReadField1(iprot thrift.TProtocol) error {
	p.Req = dragon.NewDragonSayRequest()
	if err := p.Req.Read(iprot); err != nil {
		return err
	}
	return nil
}

func (p *SampleDragonSayArgs) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("dragonSay_args"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}

	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *SampleDragonSayArgs) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("req", thrift.STRUCT, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := p.Req.Write(oprot); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *SampleDragonSayArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SampleDragonSayArgs(%+v)", *p)
}

func (p *SampleDragonSayArgs) DeepEqual(ano *SampleDragonSayArgs) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Req) {
		return false
	}
	return true
}

func (p *SampleDragonSayArgs) Field1DeepEqual(src *dragon.DragonSayRequest) bool {

	if !p.Req.DeepEqual(src) {
		return false
	}
	return true
}

type SampleDragonSayResult struct {
	Success *dragon.DragonSayResponse `thrift:"success,0,optional" frugal:"0,optional,dragon.DragonSayResponse" json:"success,omitempty"`
}

func NewSampleDragonSayResult() *SampleDragonSayResult {
	return &SampleDragonSayResult{}
}

func (p *SampleDragonSayResult) InitDefault() {
	*p = SampleDragonSayResult{}
}

var SampleDragonSayResult_Success_DEFAULT *dragon.DragonSayResponse

func (p *SampleDragonSayResult) GetSuccess() (v *dragon.DragonSayResponse) {
	if !p.IsSetSuccess() {
		return SampleDragonSayResult_Success_DEFAULT
	}
	return p.Success
}
func (p *SampleDragonSayResult) SetSuccess(x interface{}) {
	p.Success = x.(*dragon.DragonSayResponse)
}

var fieldIDToName_SampleDragonSayResult = map[int16]string{
	0: "success",
}

func (p *SampleDragonSayResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SampleDragonSayResult) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 0:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField0(iprot); err != nil {
					goto ReadFieldError
				}
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}

		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_SampleDragonSayResult[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *SampleDragonSayResult) ReadField0(iprot thrift.TProtocol) error {
	p.Success = dragon.NewDragonSayResponse()
	if err := p.Success.Read(iprot); err != nil {
		return err
	}
	return nil
}

func (p *SampleDragonSayResult) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("dragonSay_result"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField0(oprot); err != nil {
			fieldId = 0
			goto WriteFieldError
		}

	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *SampleDragonSayResult) writeField0(oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err = oprot.WriteFieldBegin("success", thrift.STRUCT, 0); err != nil {
			goto WriteFieldBeginError
		}
		if err := p.Success.Write(oprot); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 0 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 0 end error: ", p), err)
}

func (p *SampleDragonSayResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SampleDragonSayResult(%+v)", *p)
}

func (p *SampleDragonSayResult) DeepEqual(ano *SampleDragonSayResult) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field0DeepEqual(ano.Success) {
		return false
	}
	return true
}

func (p *SampleDragonSayResult) Field0DeepEqual(src *dragon.DragonSayResponse) bool {

	if !p.Success.DeepEqual(src) {
		return false
	}
	return true
}
